# Generated by Django 5.1.2 on 2024-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudantes', to='school.curso'),
        ),
    ]
