# Generated by Django 5.1.2 on 2024-10-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='telefone',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
